### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by BobyMCbobs** [ii/uedu#1]
- build a bootable Fedora/OSTree based image
- include the following software
  - Scratch
  - Sonic Pi
  - Minecraft Forge
  - an IDE?
- include a PDF or webpage for course instructions
  - webserver?
- current issues include
  - ublue images don’t cache OS container image in ISO (except some Bazzite images :eyes:)
  - Flatpaks install post-install
  - RPM for Scratch is tricky
  - building Sonic Pi from source is broken

# TODO

- [ ] generate a raw image or write to a disk
  - [ ] dynamic disk sizing (https://github.com/osbuild/bootc-image-builder/issues/52)
- [x] have an ii user pre-installed with a password of ii
- [x] auto-login the ii user with gdm
- [x] auto-expand root partition to size of disk
- [x] ensure location services + auto-timezone are enabled by default
- [x] ensure Flatpak applications are either pre-installed or auto-install on boot

**Comment by BobyMCbobs** [comment]
some things that are unknown to me are

- what type of machines will the image be deployed to?
- what's the level of internet access?

**Comment by BobyMCbobs** [comment]
Been making progress with using [_osbuild/osbuild-deploy-container_](https://github.com/osbuild/osbuild-deploy-container). A pre-installed image is able to be produced which is bootable in a VM.
I've modified the program to produce raw images to try and boot on hardware but after selecting the boot entry in the BIOS/UEFI, it stops at a blank screen; tracking it here on [_a ublue discourse thread_](https://universal-blue.discourse.group/t/building-a-bootable-qcow2-virtual-disk-image-from-an-oci-ostree-image/67/4)

**Comment by BobyMCbobs** [comment]
Noticing a slightly different disk layout in
https://github.com/osbuild/osbuild/blob/7b201db5a76a40c50cee6f17bb4ca25ff96d3e27/test/data/manifests/fedora-coreos-container.mpp.yaml#L10
so adjusted it in 
https://github.com/BobyMCbobs/osbuild-images/commit/ff033ca051738a1cf1d79e5d7e3ff2160d30635b
Doing a raw image build now

**Comment by BobyMCbobs** [comment]
This adjustment didn't yield any results

**Comment by BobyMCbobs** [comment]
The grub config in the rendered manifest looks like
```
...
{
          "type": "org.osbuild.grub2",
          "options": {
            "root_fs_uuid": "6e4ff95f-f662-45ee-a82a-bdf44a2d0b75",
            "boot_fs_uuid": "0194fdc2-fa2f-4cc0-81d3-ff12045b73c8",
            "kernel_opts": "rw console=tty0 console=ttyS0",
            "legacy": "i386-pc",
            "uefi": {
              "vendor": "fedora",
              "install": true,
              "unified": true
            },
            "greenboot": true,
            "write_cmdline": false,
            "config": {
              "default": "saved",
              "terminal_output": [
                "console"
              ],
              "timeout": 1
            }
          },
          "mounts": [
            {
              "name": "ostree-ostree/1/1/0",
              "type": "org.osbuild.ostree.deployment",
              "options": {
                "deployment": {
                  "osname": "default",
                  "ref": "ostree/1/1/0",
                  "serial": 0
                }
              }
            }
          ]
        },
...
```

meanwhile in the container mpp config it is a bit different
https://github.com/osbuild/osbuild/blob/7b201db5a76a40c50cee6f17bb4ca25ff96d3e27/test/data/manifests/fedora-coreos-container.mpp.yaml#L80

things like
- no greenboot
- no write_defaults
- partition labels (bootfs, rootfs)

**Comment by BobyMCbobs** [comment]
`bootc` now installs successfully to disk, which boots. There was something wrong with the integration between `bootc` and `bootupctl` or just `bootupctl`.
There's some difference between how `bootc` and `ostree-deploy-container` install the grub, the latter now booting.

**Comment by BobyMCbobs** [comment]
Managed to get an `ii` user pre-installed, though there's issues around the home directory not existing after boot, which makes sense.
Managed to get Flatpaks installing after boot, though there's some issues around first network connection happening.

https://github.com/BobyMCbobs/ublue-os-startingpoint/compare/07544d7d40dbe639982267ea4b0c706939779ab6..43f591643c58f3b0ce22348d6a29181f6cda3391

**Comment by BobyMCbobs** [comment]
I laid out almost the entire install process of `bootc` as shell commands to try and figure out the difference between `osbuild-deploy-container` and `bootc`, see

http://universal-blue.discourse.group/t/building-a-bootable-qcow2-virtual-disk-image-from-an-oci-ostree-image/67/13?u=calebwoodbine

this info allows me to reinstall the bootloader on top of a `osbuild-deploy-container` installed disk to get it to boot on my test system.
I would like to work with the maintainers to ensure that the bootloader is installed as expected.

**Comment by BobyMCbobs** [comment]
A todo list is now in the top comment.

**Comment by BobyMCbobs** [comment]
Managed to get a successful build with the refreshed and updated https://github.com/osbuild/bootc-image-builder
for _quay.io/fedora-ostree-desktops/silverblue:39_ and _ghcr.io/bobymcbobs/u:latest_.

There’s currently a fixed/non-variable 2GB root file system
https://github.com/osbuild/bootc-image-builder/blob/aaa2f5b/bib/cmd/bootc-image-builder/partition_tables.go#L53
which will cause limitations for some images. Exploring options there, such as auto-sizing the root filesystem for the build.

**Comment by BobyMCbobs** [comment]
Currently trying to resolve the password not being set for the ii user after first boot.

Seeing the error
```
multi-user.target: Job u-firstboot-finalise.service/start deleted to break ordering cycle starting with multi-user.target/start
```

**Comment by BobyMCbobs** [comment]
Seeing these logs from _u-firstboot-finalise.service_

```
...
... /usr/lib/u-firstboot/install-post.sh: line 12: /usr/sbin/chpasswd: Permission denied
...
```

This error doesn't make sense to me yet. The program does exist and is executable.
On one occasion, I managed to restart the service and it completed the job.
Having a tricky time trying to find the right set of `After` and `WantedBy` for the finalise service to make it run once at least _gdm.service_ begins.
